### ISSUE TITLE
Information regarding training loop data

### ISSUE THREAD

**Issue by m-muaz** [wangqiang9/Finetune-SVD#1]
Hi Wang,

Many thanks to you for the effort.

I just need a couple of clarifications regarding the data in the training loop regarding my following queries:
* So, based on your code logic and flow, I understood that the `image = batch["image"]`  variable in the train loop is a conditioning image (first frame) of the corresponding video data. Is this correct?
* Secondly, does the variable `pixel_values = batch["pixel_values"]` correspond to the sampled video frame values?
* Also, in the inner for loop in the training loop for fine tuning on video and text, where is the variable `noisy_latents` defined because I don't find any declarations of that variables before that `for` loop. Is that a typo for `latent_model_input`?

Looking forward to your response

**Comment by wangqiang9** [comment]
Hi, m-muaz,
* Yes. Because I want to fine tune the `image-to-video` model instead of the `text-to-video` model.
* Yes.
* Thanks, the error has been commited to solve.

**Comment by m-muaz** [comment]
Thanks @wangqiang9 for the response. I have a couple more questions.
* Firstly, the following code before the inner for loop has these variables 
```
...
# We detach the encoder hidden states for the first pass (video frames > 1)
# Then we make a clone of the initial state to ensure we can train it in the loop.
detached_encoder_state = encoder_hidden_states.clone().detach() # image_encoder
trainable_encoder_state = encoder_hidden_states.clone()
...
```
The variable encoder_hidden_states has never defined before this piece of code and I see that the `encoder_hidden_states` variables to be declared in the inner for loop which confuses me a bit as this seems to be a circular logical assignment. Is this a typo or am I missing something, correct me if I am wrong?

* As someone mentioned in another issue the `diffusers.EulerDiscreteScheduler` does not have a method called get velocity and since the config has `prediction type=="v_prediction"` How did you handled it? Did you defined your own function?
* Thirdly, can you share some comparative results if you got them after running your code on your dataset?

Thanks and Looking forward to your response.

**Comment by wangqiang9** [comment]
Hi, I have added the experimental results of multi-view 3D finetuning svd results in `README.md`.
