### ISSUE TITLE
AttributeError: 'EulerDiscreteScheduler' object has no attribute 'get_velocity'.

### ISSUE THREAD

**Issue by JunruiXiao** [wangqiang9/Finetune-SVD#3]
Thank you for this SVD training code!
When I run this code on webvid, it take mistakes.
![截屏2024-01-08 16 43 42](https://github.com/wangqiang9/Finetune-SVD/assets/89069159/223a39bb-b1a9-40d5-b4e9-8eb71fe44452)
at line 830, AttributeError: 'EulerDiscreteScheduler' object has no attribute 'get_velocity'.
Could you help me to solve this problem?

**Comment by glimmer16** [comment]
I met the same issue. And when ignoring the above problem, I got another mistake:
 
<img width="1111" alt="截屏2024-01-17 16 26 57" src="https://github.com/wangqiang9/Finetune-SVD/assets/66953582/4a497f6d-f3d1-42bc-860f-857753f9cbe8">
at line 857, UnboundLocalError: local variable 'encoder_hidden_states' referenced before assignment.
Looking forward to your reply.

**Comment by wangqiang9** [comment]
Hi, This problems has been solved and the code commited.
